# .readthedocs.yaml
version: 2

# Environment to build the docs
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Tell RTD where your Sphinx conf.py is
sphinx:
  configuration: docs/conf.py

# Install dependencies before building
python:
  install:
    - requirements: docs/requirements.txt
